FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
MAINTAINER Dave Walker (david.walker5@icloud.com)
COPY flightrecorder.api-1.0.0.0 /opt/flightrecorder.api-1.0.0.0
WORKDIR /opt/flightrecorder.api-1.0.0.0/bin
ENTRYPOINT [ "./FlightRecorder.Api" ]
